apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-load-balancer-conf
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  map-hash-bucket-size: "128"
  error-log-level: "notice"
  ssl-protocols: "TLSv1.1 TLSv1.2"
  enable-vts-status: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: kube-system

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: kube-system